use_frameworks!

platform :ios, '8.0'

target 'RSKitExtension_Example' do
  pod 'RSKitExtension', :path => '../'
  pod 'RSAnimator', '~> 1.0.1'
  
  target 'RSKitExtension_Tests' do
    inherit! :search_paths

    
  end
end
